### ISSUE TITLE
Custom taxonomy not available when WordPressTermContext->insert()

### ISSUE THREAD

**Issue by davidbenton** [stephenharris/WordPressBehatExtension#13]
My plugin has a custom taxonomy that works, but when I try to create some terms like:

```
Background:
  Given [...]
  And there are plugins
        | plugin              | status  |
        | library/library.php | enabled |
  And there are document_tag terms
        | name      | slug | description   |
        | English   | en   |               |
        | Spanish   | es   |               |
```

...I get an error: "exception 'InvalidArgumentException' with message 'Invalid taxonomy term information schema: Invalid taxonomy.' in vendor/stephenharris/wordpress-behat-extension/src/Context/Terms/WordPressTermTrait.php:21"

This seems to be because the taxonomy is not available/registered when the context runs wp_insert_term(). If I run `get_taxonomies()` in the exception, my taxonomy isn't listed, but if I run `is_plugin_active('library/library.php')`, it is active.

I'll keep trying to debug, but would welcome guidance. I'm new to behat, so could definitely be missing something simple.

Note: I can run (and pass) scenarios where the same terms are created, but when setting them up as background, I get an error.

**Comment by stephenharris** [comment]
On what hook are you registering the taxonomy? In Event Organiser, I've registered a taxonomy on the `init` hook, and that works fine: https://github.com/stephenharris/Event-Organiser/blob/develop/features/events-admin-list.feature#L25

Given you can't see it in `get_taxonomies()` then it can't have been registered (yet), so it's likely either the your callback for registering the taxonomy isn't being registered with the hook, the hook isn't firing or there's some conditional in your callback which means it's not registering the taxonomy.

**Comment by davidbenton** [comment]
I'm registering the taxonomy on init. The taxonomy works as expected in scenarios, so it is loading, and it's not clear to me what the difference is between this and Event Organizer's custom taxonomy. I'm using v0.4.0 of this extension, and I see you're using the develop branch on Event Organizer, so I'll try that and see if it changes anything.

**Comment by stephenharris** [comment]
Keep in mind the changelog: https://github.com/stephenharris/WordPressBehatExtension/blob/develop/CHANGELOG.md - there are a few breaking changes.

Also, by "scenerios" I guess you mean scenerios where the "user" interacts with the browser (e.g. "I go to Posts > Document Tags"). There is a difference between that and the steps which create data. Specifically the former behaves like a normal WordPress install. For the later, you are just loading the WordPress codebase (where you're running the tests) and using its API. 

There are some subtle differences between the two - but you would probably have to be doing something unusual for it to be a problem. 

One thing to check is to write to your error logs to confirm you're taxonomy is being registered. You'll wan to ignore steps which access the install via a browser.

**Comment by davidbenton** [comment]
Yeah, understood. The browser/mink interactions work, whereas the WP APIs (via `require_once('wp-load.php')` or similar) are where I'm not seeing my taxonomy. Nothing too weird about how I'm registering it. It uses an anonymous function for the callback, but I should be using the same version of php in mink and WP APIs, so I don't see how that could be an issue.

Good plan. I'll try logging some debug output.

Looks like the version of the extension used in Event Organizer's composer.lock is older than v0.4.0, but I still get the error with that. Will return to v0.4.0 for more debugging.

Thanks for your help.

**Comment by davidbenton** [comment]
Aha! Event Organizer's CPT and taxonomies work because of [these lines](https://github.com/stephenharris/Event-Organiser/blob/develop/includes/event-organiser-install.php#L135-L136). If they're not manually registered, they don't get registered before `WordPressTermTrait->insert()` is run.

I guess this means the init hook isn't being run. What's the purpose of manually calling those register functions? I've never done that in a plugin before.

**Comment by davidbenton** [comment]
I can confirm that init is not run during a simple feature definition, at least after the plugin is loaded. Checked action hooks using [this method](http://wordpress.stackexchange.com/a/250293/50131).

When opening a page on the same WP site through a browser, many more actions are run (makes sense to me, as I think directly requiring wp-load skips a lot of theme stuff?), including init.

**Comment by stephenharris** [comment]
Ah, that's good to know.

The purpose of manually registering them is because it registers rewrite rules (which is why you flush them in the proceeding lines).

**Comment by davidbenton** [comment]
Gotcha. The need to visit options-permalink.php after rewrite changes has always been a minor annoyance, but none of my plugins are for public consumption, so it's not been a big deal. I guess I can solve that and this issue with one change.

Would you consider this a bug and want a PR, or is this project essentially deprecated in favor of WordHat? If you want a PR, I can work on one, but any thoughts on how to ensure custom post types and taxonomies are recognized?

**Comment by davidbenton** [comment]
Adding the acitvation hook as recommended at https://codex.wordpress.org/Function_Reference/flush_rewrite_rules solved this for me. This may be a bug, but shouldn't affect well-built plugins, and hopefully if anyone else has issues they'll find this thread.

**Comment by stephenharris** [comment]
@davidbenton This could catch people out. The reason this happens is that the `init` hook is only fired once per scenerio (at least, when considering the `WP API` steps). This is because behat runs in a single PHP thread, and so WordPress loaded once. Since the database is reset, there are no plugins active when the hook is triggered, and thus unless plugins also register their CPTs (etc) when they are activated, they will not be registered.

There is no easy fix to this unfortunately. [WordHat](https://wordhat.info), however does allow you to work around this. You can either use the `wpcli` driver, in which the `init` hook is triggered on each invocation. Or you can use the `wpapi` driver (which is similar to this plug-in) - but you can set up the database so that it's in a state in which your plugins are active prior to the tests being run. This is possible because WordHat does not reset the database before a scenerio.
