### ISSUE TITLE
Trouble using with MySQL sitting at remote location

### ISSUE THREAD

**Issue by rask** [stephenharris/WordPressBehatExtension#19]
Current configuration setup seems to force `mysqli` connections to connect always to `localhost`. This creates issues in setups where the database not running on `localhost`.

Example: Gitlab CI and running MySQL as a Docker service container (which results MySQL being available at hostname `mysql`, not `localhost`).

Errors that appear are similar to

    PHP Warning:  mysqli::__construct(): (HY000/2002): No such file or directory in 
        /path/to/project/vendor/stephenharris/wordpress-behat-extension/src/Context/Initializer/WordPressContextInitializer.php
        on line 170

Could the `behat.yml` connection config be expanded to include an option to change the MySQL hostname/IP?

**Comment by stephenharris** [comment]
I'd happily merge in a PR for such a change, but I'm not actively maintaining this project any more. I'm currently working on [WordHat](https://wordhat.info/).

**Comment by rask** [comment]
I'll send a PR for you. Is WordHat something that can replace this library as is when doing acceptance testing and similar?

**Comment by stephenharris** [comment]
Thanks @rask. WordHat serves the same purpose. There are some importance differences: WordHat does not install WordPress, overwrite the `wp-config.php` or reset the database between scenarios - you have to handle all that. WordHat supports other ways of communicating with the WordPress install (i.e. via `wp-cli`) - which allows you to run tests against a remote install (even smoke tests against a live install). There isn't however, full parity in terms of step definitions - WordHat is getting more and more step definitions, but there are some provided by this extension (specifically those relating to e-mails) which cannot be implemented by WordHat alone.

**Comment by rask** [comment]
I see. Currently, I just require a temporary test installation and WordPress core being loaded. I'll read some more about WordHat. Thank you.
